import Head from 'next/head'
import { Flex,Button} from '@chakra-ui/react'
import { InputComponent } from '../components/input'


export default function SignIn() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Flex 
      w="100vw"
      h="100vh"
      align="center"
      justify="center"
      >
        <Flex as="form" 
        w="100%" 
        maxWidth="360px" 
        bg="gray.800" 
        p="8" 
        borderRadius="8" 
        flexDir="column" 
        gap="4"
        >
          <InputComponent type="email" name='email' label='Email:'/>
          <InputComponent type="password" name='password' label='Password:'/>
          <Button 
          type='submit' 
          mt="6" 
          colorScheme="pink"
          >
            Entrar
          </Button>
        </Flex>
      </Flex>
      </main>
    </>
  )
}
